// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whdbyyvyhrdqgswunzvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZGJ5eXZ5aHJkcWdzd3VuenZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDE2MDIsImV4cCI6MjA2MDAxNzYwMn0.cCzFcF1z5PuW9uBX2zymusAVL5gxDoYYhMfXLYZVv7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);